---
resources:
  pipelines:
    - pipeline: AWSInit 
      source: azure-aws.yml

#    - pipeline: Crossplane 
#      source: azure-crossplane.yml
#      trigger:
#        paths:
#          exclude:
#            - './*'
#          include:
#            - 'aws/crossplane/*'
#        branches:
#          include:
#            - main

