---
resources:
  pipelines:
    - pipeline: AWSInit 
      source: azure-aws.yml
      trigger:
        paths:
          exclude:
            - './*'
          include:
            - 'aws/crossplane/*'
        branches:
          include:
            - main

#    - pipeline: Crossplane 
#      source: azure-crossplane.yml
#      trigger:
#        paths:
#          exclude:
#            - './*'
#          include:
#            - 'aws/crossplane/*'
#        branches:
#          include:
#            - main

