# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: MBP

steps:

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.0.0'
    
- task: TerraformCLI@0
  displayName: 'Terraform Init'
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/aws'
    backendType: 'aws'
    allowTelemetryCollection: false
    backendServiceAws: 'WayOfTheSys'
    backendAwsRegion: 'us-east-2'
    backendAwsBucket: 'wayofthesys'
    backendAwsKey: 'bank-prod.tfstate'


- task: TerraformCLI@0
  displayName: 'Terraform Validate'
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/aws'
    allowTelemetryCollection: false

- task: TerraformCLI@0 
  displayName: 'Terraform Plan'
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/aws'
    commandOptions: '-var-file="prod.tfvars" -out="-out=$(System.DefaultWorkingDirectory)/bank-prod.tfplan) -detailed-exitcode"' 
    allowTelemetryCollection: false
    publishPlanResults: 'bank-prod.tfplan'

- task: TerraformCLI@0
  displayName: 'Terraform Apply'
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/aws'
    commandOptions: '$(System.DefaultWorkingDirectory)/bank-prod.tfplan'
    allowTelemetryCollection: false
    providerServiceAws: 'WayOfTheSys'
    providerAwsRegion: 'us-east-2'

