apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl 
spec:
  acme:
    email: {{ .Values.zerossl_email }}
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: {{ .Values.zerossl_eab_key_id }}
      keySecretRef:
        name: zerossl-eab-hmac-key 
        key: secret
      keyAlgorithm: HS256
    privateKeySecretRef:
        name: prod 
    solvers:
    - selector:
        dnsZones: 
          - "wayofthesys.com"
      dns01:
        route53:
          accessKeyID: AKIATMXSQTLMQGGS2MP7
          region: us-east-2
          secretAccessKeySecretRef:
            name: externaldns
            key: secret-key
    - http01:
        ingress:
          class: istio
    
